---
- name: Install UFW
  apt:
    name: ufw
    state: latest
    force_apt_get: yes

- name: Allow OpenSSH
  ufw:
    rule: allow
    name: OpenSSH
  notify: ufw_reload

- name: Enable UFW
  ufw:
    state: enabled
