---
- name: Ensure ufw is installed
  apt:
    name: ufw
    state: present
    force_apt_get: yes

- name: Ensure OpenSSH is installed
  apt:
    name: ssh
    state: present
    force_apt_get: yes

- name: Allow OpenSSH
  ufw:
    rule: allow
    name: OpenSSH
  notify: ufw_reload

- name: Set ufw rules
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop: "{{ ufw_rules }}"
  notify: ufw_reload

- name: Enable UFW
  ufw:
    state: enabled
