---
- name: Ensure ufw is installed
  apt:
    name: ufw
    state: present
    force_apt_get: yes

# FIXME: This task is needed to fix an issue that causes the
# `ufw status verbose` command to fail. It is not known why
# ensuring ssh is installed will solve the error.
- name: Ensure ssh is installed
  apt:
    name: ssh
    state: present
    force_apt_get: yes

- name: Set ufw rules
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop: "{{ ufw_rules }}"
  notify: ufw_reload

- name: Enable UFW
  ufw:
    state: enabled
